export {
  contractCard,
  ndaCard,
  invoiceCard,
  proposalCard,
  letterCard,
  agreementCard,
  documentCard,
  signatureCard,
  taskCard,
  noteCard,
  linkCard,
  getDocumentCard,
  getServiceCard,
} from "./generated.js";
