/**
 * Generates a preview card SVG for MCP tool responses.
 * Returns a base64-encoded PNG-compatible SVG string.
 *
 * Cards are 600×315 (Open Graph ratio) — renders well in chat UIs.
 */

interface CardConfig {
  label: string;
  accent: string;
  icon: string; // SVG path data
  bgPattern?: boolean;
}

function renderCard(config: CardConfig): string {
  const { label, accent, icon, bgPattern = true } = config;

  // Subtle dot pattern for depth
  const pattern = bgPattern
    ? `<defs>
        <pattern id="dots" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
          <circle cx="2" cy="2" r="0.8" fill="${accent}" opacity="0.07"/>
        </pattern>
      </defs>
      <rect width="600" height="315" fill="url(#dots)"/>`
    : "";

  return `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="315" viewBox="0 0 600 315">
  <!-- Background -->
  <rect width="600" height="315" rx="12" fill="#0a0a0a"/>
  ${pattern}

  <!-- Accent bar -->
  <rect x="0" y="0" width="600" height="4" rx="2" fill="${accent}"/>

  <!-- Icon -->
  <g transform="translate(40, 80)">
    <rect width="80" height="80" rx="16" fill="${accent}" opacity="0.12"/>
    <g transform="translate(20, 20)">
      <path d="${icon}" fill="${accent}" transform="scale(1.667)"/>
    </g>
  </g>

  <!-- Label -->
  <text x="140" y="118" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="22" font-weight="600" fill="#f5f5f5">${label}</text>
  <text x="140" y="145" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="14" fill="#737373">Cometa</text>

  <!-- Bottom border -->
  <rect x="40" y="200" width="520" height="1" fill="#262626"/>

  <!-- Branding -->
  <text x="40" y="270" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="12" fill="#525252">Generated by Cometa</text>
  <text x="560" y="270" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" font-size="12" fill="#525252" text-anchor="end">cometa.co</text>
</svg>`;
}

function toBase64(svg: string): string {
  return Buffer.from(svg).toString("base64");
}

export function createCard(config: CardConfig): string {
  return toBase64(renderCard(config));
}

export type { CardConfig };
