/**
 * Reads HTML view files from src/views/ and generates a TypeScript module
 * that exports them as strings. No build step needed — HTML files are self-contained.
 *
 * Run: bun scripts/generate-views.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const VIEWS_DIR = join(__dirname, "../src/views");
const OUT_FILE = join(VIEWS_DIR, "generated.ts");

const files = readdirSync(VIEWS_DIR).filter((f) => f.endsWith(".html"));

const lines: string[] = [
  "// Auto-generated by scripts/generate-views.ts — do not edit manually",
  "",
];

for (const file of files) {
  const html = readFileSync(join(VIEWS_DIR, file), "utf-8");
  const name =
    basename(file, ".html").replace(/-([a-z])/g, (_, c) => c.toUpperCase()) +
    "View";
  lines.push(`export const ${name} = ${JSON.stringify(html)};`);
}

lines.push("");
lines.push("export const viewMap: Record<string, string> = {");
for (const file of files) {
  const key = basename(file, ".html");
  const name =
    key.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "View";
  lines.push(`  "${key}": ${name},`);
}
lines.push("};");
lines.push("");
lines.push("export function getView(name: string): string | undefined {");
lines.push("  return viewMap[name];");
lines.push("}");

writeFileSync(OUT_FILE, lines.join("\n") + "\n");
console.log(`Generated ${files.length} views → src/views/generated.ts`);
